server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Прокси для запросов к API Green-API
    location /api/ {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass https://1105.api.green-api.com;
        proxy_set_header Host 1105.api.green-api.com;

        # Добавляем CORS-заголовки
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Content-Type' always;

        if ($request_method = 'OPTIONS') {
            return 204;
        }
    }
}
